# automatically generated by the FlatBuffers compiler, do not modify

# namespace: DataMsgNameSpace

class OperationType(object):
    FILTER_TIME_UPDATE = 0
    FILTER_MEAS_UPDATE = 1
    SENSOR = 2
    FILTER_PARAM_ESTIMATION = 3
    GROUND_TRUTH = 4

