#include "Eigen/Dense"

enum DataType { NOISE, DISTURBANCE, STATE, OUTPUT };

enum TimeUpdateType { STATE_UPDATE, OUTPUT_UPDATE };

enum OperationType { FILTER_TIME_UPDATE, FILTER_MEAS_UPDATE, SENSOR, FILTER_PARAM_ESTIMATION, GROUND_TRUTH};
