###### CPPZMQ
set (CMAKE_3RDPARTY_CPPZMQ_SRC_DIR "${CMAKE_3RDPARTY_DIR}/Ext-CPPZMQ")
set (CMAKE_3RDPARTY_CPPZMQ_BUILD_DIR "${CMAKE_3RDPARTY_DIR}/Ext-CPPZMQ-build")
# CPPZMQ CLONE
set (CPPZMQ_TAG "v4.5.0")
message( STATUS "Downloading CPPZMQ ${CPPZMQ_TAG} (to ${CMAKE_3RDPARTY_CPPZMQ_SRC_DIR})...")
EXEC_PROGRAM( "git clone https://github.com/zeromq/cppzmq.git -b${CPPZMQ_TAG} \"${CMAKE_3RDPARTY_CPPZMQ_SRC_DIR}\"" )
message ( STATUS " succeeded. CMake configure started....")
# Call configure, generate and build (Release & Debug) on the externals
message(STATUS "Generating solution for CPPZMQ")
EXEC_PROGRAM(${CMAKE_COMMAND} \"${CMAKE_3RDPARTY_CPPZMQ_SRC_DIR}\" ARGS 
	\"${GENERATOR_ARGUMENT}\" \"-S${CMAKE_3RDPARTY_CPPZMQ_SRC_DIR}\" \"-B${CMAKE_3RDPARTY_CPPZMQ_BUILD_DIR}\"
	-DCMAKE_INSTALL_PREFIX=\"${3RDPARTY_INSTALL_PREFIX}\"
	-DENABLE_DRAFTS=FALSE
	-DBUILD_TESTING=FALSE
	-DCPPZMQ_BUILD_TESTS=FALSE
	${EXTERNAL_FLAG_SETTER}
	)
message(STATUS "Installing CPPZMQ...")
EXEC_PROGRAM(${CMAKE_COMMAND} ARGS
	--install \"${CMAKE_3RDPARTY_CPPZMQ_BUILD_DIR}\" --config Release )
message(STATUS "done.")