// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MSG_DATAMSGNAMESPACE_H_
#define FLATBUFFERS_GENERATED_MSG_DATAMSGNAMESPACE_H_

#include "flatbuffers/flatbuffers.h"

namespace DataMsgNameSpace {

struct Msg;

enum DataType {
  DataType_NOISE = 0,
  DataType_DISTURBANCE = 1,
  DataType_STATE = 2,
  DataType_OUTPUT = 3,
  DataType_MIN = DataType_NOISE,
  DataType_MAX = DataType_OUTPUT
};

inline const DataType (&EnumValuesDataType())[4] {
  static const DataType values[] = {
    DataType_NOISE,
    DataType_DISTURBANCE,
    DataType_STATE,
    DataType_OUTPUT
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[] = {
    "NOISE",
    "DISTURBANCE",
    "STATE",
    "OUTPUT",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (e < DataType_NOISE || e > DataType_OUTPUT) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

enum OperationType {
  OperationType_FILTER_TIME_UPDATE = 0,
  OperationType_FILTER_MEAS_UPDATE = 1,
  OperationType_SENSOR = 2,
  OperationType_FILTER_PARAM_ESTIMATION = 3,
  OperationType_GROUND_TRUTH = 4,
  OperationType_MIN = OperationType_FILTER_TIME_UPDATE,
  OperationType_MAX = OperationType_GROUND_TRUTH
};

inline const OperationType (&EnumValuesOperationType())[5] {
  static const OperationType values[] = {
    OperationType_FILTER_TIME_UPDATE,
    OperationType_FILTER_MEAS_UPDATE,
    OperationType_SENSOR,
    OperationType_FILTER_PARAM_ESTIMATION,
    OperationType_GROUND_TRUTH
  };
  return values;
}

inline const char * const *EnumNamesOperationType() {
  static const char * const names[] = {
    "FILTER_TIME_UPDATE",
    "FILTER_MEAS_UPDATE",
    "SENSOR",
    "FILTER_PARAM_ESTIMATION",
    "GROUND_TRUTH",
    nullptr
  };
  return names;
}

inline const char *EnumNameOperationType(OperationType e) {
  if (e < OperationType_FILTER_TIME_UPDATE || e > OperationType_GROUND_TRUTH) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOperationType()[index];
}

struct Msg FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_SOURCE = 6,
    VT_SENSORID = 8,
    VT_VALUE_VECTOR = 10,
    VT_VARIANCE_MATRIX = 12,
    VT_TIMESTAMP_IN_US = 14
  };
  DataType type() const {
    return static_cast<DataType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  OperationType source() const {
    return static_cast<OperationType>(GetField<uint8_t>(VT_SOURCE, 0));
  }
  int32_t sensorID() const {
    return GetField<int32_t>(VT_SENSORID, 0);
  }
  const flatbuffers::Vector<float> *value_vector() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_VALUE_VECTOR);
  }
  const flatbuffers::Vector<float> *variance_matrix() const {
    return GetPointer<const flatbuffers::Vector<float> *>(VT_VARIANCE_MATRIX);
  }
  int64_t timestamp_in_us() const {
    return GetField<int64_t>(VT_TIMESTAMP_IN_US, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE) &&
           VerifyField<uint8_t>(verifier, VT_SOURCE) &&
           VerifyField<int32_t>(verifier, VT_SENSORID) &&
           VerifyOffset(verifier, VT_VALUE_VECTOR) &&
           verifier.VerifyVector(value_vector()) &&
           VerifyOffset(verifier, VT_VARIANCE_MATRIX) &&
           verifier.VerifyVector(variance_matrix()) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP_IN_US) &&
           verifier.EndTable();
  }
};

struct MsgBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_type(DataType type) {
    fbb_.AddElement<uint8_t>(Msg::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_source(OperationType source) {
    fbb_.AddElement<uint8_t>(Msg::VT_SOURCE, static_cast<uint8_t>(source), 0);
  }
  void add_sensorID(int32_t sensorID) {
    fbb_.AddElement<int32_t>(Msg::VT_SENSORID, sensorID, 0);
  }
  void add_value_vector(flatbuffers::Offset<flatbuffers::Vector<float>> value_vector) {
    fbb_.AddOffset(Msg::VT_VALUE_VECTOR, value_vector);
  }
  void add_variance_matrix(flatbuffers::Offset<flatbuffers::Vector<float>> variance_matrix) {
    fbb_.AddOffset(Msg::VT_VARIANCE_MATRIX, variance_matrix);
  }
  void add_timestamp_in_us(int64_t timestamp_in_us) {
    fbb_.AddElement<int64_t>(Msg::VT_TIMESTAMP_IN_US, timestamp_in_us, 0);
  }
  explicit MsgBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MsgBuilder &operator=(const MsgBuilder &);
  flatbuffers::Offset<Msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Msg>(end);
    return o;
  }
};

inline flatbuffers::Offset<Msg> CreateMsg(
    flatbuffers::FlatBufferBuilder &_fbb,
    DataType type = DataType_NOISE,
    OperationType source = OperationType_FILTER_TIME_UPDATE,
    int32_t sensorID = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> value_vector = 0,
    flatbuffers::Offset<flatbuffers::Vector<float>> variance_matrix = 0,
    int64_t timestamp_in_us = 0) {
  MsgBuilder builder_(_fbb);
  builder_.add_timestamp_in_us(timestamp_in_us);
  builder_.add_variance_matrix(variance_matrix);
  builder_.add_value_vector(value_vector);
  builder_.add_sensorID(sensorID);
  builder_.add_source(source);
  builder_.add_type(type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Msg> CreateMsgDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    DataType type = DataType_NOISE,
    OperationType source = OperationType_FILTER_TIME_UPDATE,
    int32_t sensorID = 0,
    const std::vector<float> *value_vector = nullptr,
    const std::vector<float> *variance_matrix = nullptr,
    int64_t timestamp_in_us = 0) {
  auto value_vector__ = value_vector ? _fbb.CreateVector<float>(*value_vector) : 0;
  auto variance_matrix__ = variance_matrix ? _fbb.CreateVector<float>(*variance_matrix) : 0;
  return DataMsgNameSpace::CreateMsg(
      _fbb,
      type,
      source,
      sensorID,
      value_vector__,
      variance_matrix__,
      timestamp_in_us);
}

inline const DataMsgNameSpace::Msg *GetMsg(const void *buf) {
  return flatbuffers::GetRoot<DataMsgNameSpace::Msg>(buf);
}

inline const DataMsgNameSpace::Msg *GetSizePrefixedMsg(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<DataMsgNameSpace::Msg>(buf);
}

inline bool VerifyMsgBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<DataMsgNameSpace::Msg>(nullptr);
}

inline bool VerifySizePrefixedMsgBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<DataMsgNameSpace::Msg>(nullptr);
}

inline void FinishMsgBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DataMsgNameSpace::Msg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMsgBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<DataMsgNameSpace::Msg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DataMsgNameSpace

#endif  // FLATBUFFERS_GENERATED_MSG_DATAMSGNAMESPACE_H_
